name: ci-golang-workflow
on: [push]
jobs: 
  check-app: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: 
          go-version: '>=1.15.0'
      - run: go test
      - run: go run math.go